# Python Numpy
Numpy is a general-purpose array-processing package. 
It provides a high-performance multidimensional array 
object, and tools for working with these arrays

# Creating a Numpy Array:
    Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining     the
    size of the Array.
## Note: 
    Type of array can be explicitly defined while creating the array.

In [18]:
"""
 Python program for Creation of Arrays
"""
import numpy as np
 
# A rank 1 Array
a1 = np.array([1, 2, 3])
print("An array with Rank 1: \n",a1)
 
# A rank 2 Array
a2 = np.array([[1, 2, 3],
                [4, 5, 6]])
print(" an array with Rank 2: \n", a2)
 
# Creating an array from tuple
a3 = np.array((1, 3, 2))
print("\n an array created using "
      "passed tuple:\n", a3)
a4 = np.array([{1,3,5},
             {2,3,4},
             {4,5,6}])
# an array made from dictionary
print("\n an arry of dictionary:\n", a4)
print(type(a4))


An array with Rank 1: 
 [1 2 3]
 an array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

 an array created using passed tuple:
 [1 3 2]

 an arry of dictionary:
 [{1, 3, 5} {2, 3, 4} {4, 5, 6}]
<class 'numpy.ndarray'>


In [30]:
a1 = np.array([[1,2,3],
             [4,5,6]])
print(a1)
a2 = np.array([[1,0,4],
              [3,6,7]])
print('\n', a2)

# addition on two numpy operation
print('\n',a1+a2)

#subtraction of two numpy array
print('\n', a1- a2)

# adding a given element to every element of the array

print('\n', a1+(int(input("enter the number you want to add"))))



[[1 2 3]
 [4 5 6]]

 [[1 0 4]
 [3 6 7]]

 [[ 2  2  7]
 [ 7 11 13]]

 [[ 0  2 -1]
 [ 1 -1 -1]]
enter the number you want to add10

 [[11 12 13]
 [14 15 16]]
