#  Array indexing
     Numpy offers several ways to index into arrays.

     Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be
     multidimensional, you must specify a slice for each dimension of the array:

In [4]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a,'\n')

#using slicing to create a subArray
print("new sub Array:")
b = a[:2, 1:3]
print(b)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

new sub Array:
[[2 3]
 [6 7]]


 
    A slice of an array is a view into the same data, so modifying it will modify the
    original array.



In [16]:

# print(a[0, 1])  
# print("printing b[0,0]", '\n')
# b[0, 0] = 77    
# print("printing a[0,1]")
# print(a[0, 1])

# """b[0, 0] is the same piece of data as a[0, 1]"""

77
printing b[0,0] 

printing a[0,1]
77


'b[0, 0] is the same piece of data as a[0, 1]'


#    
    You can also mix integer indexing with slice indexing. However, doing so will yield 
    an array of lower rank than the original array. 
## Note:-
     that this is quite different from the way that MATLAB handles array slicing:

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
"""creating An Array of shape (3,4)"""

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


'creating An Array of shape (3,4)'

###### Two ways of accessing the data in the middle row of the array.
     Mixing integer indexing with slices yields an array of lower rank, 
     while using only slices yields an array of the same rank as the original array:

In [37]:
print("row1")
row1 = a[1,:]
print(row1, row1.shape)

print("row2")
row2 = a[1 :2, :]
print(row2, row2.shape)

row = a[[2],  :]
print("row3")
print(row2, row2.shape)

print('\n',"main array")
print(a, a.shape)


row1
[5 6 7 8] (4,)
row2
[[5 6 7 8]] (1, 4)
row3
[[5 6 7 8]] (1, 4)

 main array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [38]:
# We can make the same distinction when accessing columns of an array:
col1 = a[:, 1]
col2 = a[:, 1:2]
print(col1, col1.shape)
print()
print(col2, col2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


# Integer array indexing: 
      When you index into numpy arrays using slicing, the resulting array view will 
      always be a subarray of the original array. In contrast, integer array indexing
      allows you to construct arbitrary arrays using the data from another array. 
    

In [52]:
a = np.array([[1,2], [3, 4], [5, 6]])

"""An example of integer array indexing.
 The returned array will have shape (3,) """

print(a[[0, 1, 2], [0, 1, 0]])

"""The above example of integer array indexing is equivalent to this:"""
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [61]:
""" 
 When using integer array indexing, you can reuse the same
element from the source array:
"""
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]
