

    One useful trick with integer array indexing is selecting or mutating one element 
    from each row of a matrix:

In [8]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b] ) # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [11]:
a[np.arange(4), b] += 10
print(a)
"""Adding 10 in all those 4 elememt we got above"""

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# Boolean array indexing: 
    Boolean array indexing lets you pick out arbitrary elements of an array. 
    Frequently this type of indexing is used to select the elements of an array 
    that satisfy some condition. Here is an example:

In [13]:
import numpy as np
"""
  Find the elements of a that are bigger than 2;
  this returns a numpy array of Booleans of the same
  hape as a, where each slot of bool_idx tells
  whether that element of a is > 2.

"""
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  

print(bool_idx)


[[False False]
 [ True  True]
 [ True  True]]
